### ISSUE TITLE
Can't build on Fedora 39

### ISSUE THREAD

**Issue by Enderteck** [kgmt0/megapixels#14]
Here is what I get when doing meson build.

Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)

meson.build:4:9: ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake

gtk4-4.12.5-1.fc39.x86_64 is already installed.

**Comment by kgmt0** [comment]
Do you have `gtk4-devel` installed?

**Comment by kgmt0** [comment]
`gtk4-devel` is technically a part of `gtk4`. It's just that some distros split development files into their own packages.

It could be helpful to add a note about that in the README, but I think that's better handled upstream. This repo is only meant to have patches for PPP.
