### ISSUE TITLE
Properly name this repo as **fork**

### ISSUE THREAD

**Issue by magdesign** [kgmt0/megapixels#18]
After talking to the creator of megapixels, i figured out that this here is a fork of the [original version](https://gitlab.com/megapixels-org). 
please be kind enough to tell this in the README.md

Thank you!

**Comment by kgmt0** [comment]
I updated the text under the About section of the page to make this more clear. I can't change README.md without adding a new commit so I want to avoid that. It makes merge conflicts more likely when I pull from upstream.
