### ISSUE TITLE
cannot compile: gtk/gtk.h no such file or directory

### ISSUE THREAD

**Issue by TheKrafter** [kgmt0/megapixels#2]
when trying to compile, going thru the steps in the readme and installing all the dependencies, i run into an error when running `ninja`. here is the log: https://paste.fizz.red/sanapubafu.php. the main error is that it cannot find `gtk/gtk.h` from the include in each file. i have gtk 3 and 4 installed, and `meson build` runs fine without any errors.

**Comment by kgmt0** [comment]
The link for the log isn't working for me, but I think this is probably a problem with your setup.

Are you able to compile the [upstream version](https://gitlab.com/postmarketOS/megapixels)? If not, that would be a good place to start.

**Comment by TheKrafter** [comment]
yeah, i get the same error with upstream
