### ISSUE TITLE
Testing the camera on PPP results

### ISSUE THREAD

**Issue by jsarkari** [kgmt0/megapixels#4]
So I tested this by creating the pine64,pinephone-pro.ini file in the config folder with the suggested details as a test and ran the megapixels app via the terminal to see how far it got.

1. On Manjaro Phosh (eMMC):

Found config file at /usr/share/megapixels/config/pine64,pinephone-pro.ini ... good start!
Adding camera rear from config
Could not find camera entity matching 'imx258'

Opening the app via the app does nothing however, I have found a new file in my /home/manjaro folder: "frame.raw"

2. On postmarketOS gnome mobile (SD Card) ... like to live on the Edge!

Found config file at /usr/share/megapixels/config/pine64,pinephone-pro.ini ... good start!
Adding camera rear from config
MPDevice: MEDIA_IOC_SETUP_LINK error 22, Invalid argument
MPCamera: VIDIOC_SUBDEV_S_FRAME_INTERVAL error 25, Not a tty
MPDevice: MEDIA_IOC_SETUP_LINK error 22, Invalid argument
MPCamera: VIDIOC_SUBDEV_S_FRAME_INTERVAL error 25, Not a tty
Initialized OpenGL ES 3.1
MPCamera: VIDIOC_STREAMON error 32, Broken pipe
MPCamera: VIDIOC_DQBUF error 22, Invalid argument
Segmentation fault

Opening the app via the app does nothing, however, there is no new file produced in my /home/user folder.

**Comment by philmmanjaro** [comment]
Manjaro ships **megapixels-ppp** but it seems since kernel 6.0 it won't start anymore. You can try with older kernels: https://gitlab.manjaro.org/manjaro-arm/packages/core/linux-pinephonepro/-/pipelines

**Comment by philmmanjaro** [comment]
V4L2 apparently doesn't have as strict backwards compatibility guarantees, and mainline changed the media graph for Rockchip ISPs. megapixels need to be updated

**Comment by kgmt0** [comment]
With 8721f29e27f21111c439ee45f4ea76b56017d016, it should start working again. Only the config file needed to be updated, so you can just copy over the config file if you already have a previous version installed.

**Comment by philmmanjaro** [comment]
Yes, it works again. For 6.1 the selfie cam will be renamed: https://github.com/kgmt0/megapixels/issues/5
