### ISSUE TITLE
Kali nethunter 5.19 PPP

### ISSUE THREAD

**Issue by phodina** [kgmt0/megapixels#8]
Hi @kgmt0,

I've wanted to test the camera on the Kali Nethunter, but seems the device tree is missing some node:

```
uname -a
Linux kali 5.19-rockchip #1 SMP PREEMPT_DYNAMIC Fri Oct 28 11:24:25 UTC 2022 aarch64 GNU/Linux
```
```
/gnu/store/50kzj741d895vhgasi7g7i8rzwpbz96x-megapixels-1.6.0/bin/megapixels
Found config file at /gnu/store/50kzj741d895vhgasi7g7i8rzwpbz96x-megapixels-1.6.0/share/megapixels/config/pine64,pinephone-pro.ini
Adding camera rear from config
Adding camera front from config
Initializing postprocessor gsetting
Found postprocessor script at /gnu/store/50kzj741d895vhgasi7g7i8rzwpbz96x-megapixels-1.6.0/share/megapixels/postprocess.sh
Initialized postprocessor to /gnu/store/50kzj741d895vhgasi7g7i8rzwpbz96x-megapixels-1.6.0/share/megapixels/postprocess.sh
Could not find /dev/media* node matching 'rkisp1'
```

What kernel commit and device tree should I use?

Also do you plan to upstream the changes to https://gitlab.com/postmarketOS/megapixels?

FIY: I'm using Guix package with the latest commit `3dc718a0626fb89b364b468ba85d9aded41e2f91`.

**Comment by kgmt0** [comment]
>What kernel commit and device tree should I use?

I tested with [linux-megi 6.0.8 from Arch Linux ARM](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/14ecda45f6cb4fa2af462efb51082e31babbcaf0/PKGBUILDS/pine64/linux-megi/PKGBUILD).

> Also do you plan to upstream the changes to https://gitlab.com/postmarketOS/megapixels?

Yes, but there's still some work to be done.

**Comment by phodina** [comment]
Okay, I'll recompile the kernel and test again.  Thanks :-)

**Comment by phodina** [comment]
Hi I've moved to PostmarketOS and the recent kernel. Since there's already a ticket I'll continue there.

https://github.com/kgmt0/megapixels/issues/7
